service: youtube-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  youtubeHelloFn:
    handler: hello.handler
    events:
      - httpApi: 'GET /hello'
  youtubeByFn:
    handler: bye.handler
    events:
      - httpApi: 'GET /bye'